source :gemcutter

gem "builder"
gem "data_objects", "0.9.12"
gem "datamapper", "0.9.11"
gem "dm-is-searchable", "0.9.11"
gem "do_sqlite3", "0.9.12"
gem "erubis"
gem "fastercsv"
gem "json"
gem "logging"
gem "mail_builder"
gem "rack", "~> 1.0.1"
gem "rake"
gem "RedCloth"
gem "sanitize"
gem "tmail"

gem "harbor", "0.18.33", :git => "git://github.com/wiecklabs/harbor.git"
gem "port_authority", "1.7.9", :git => "git://github.com/wiecklabs/port_authority.git"
gem "ui", "0.7.42", :git => "git://github.com/wiecklabs/ui.git"
